export * from './residence-hero-section'
export * from './residence-benefits-section'
export * from './residence-programs-section'
export * from './residence-cta-section'
export * from './residence-benefit-requirements-section'